#!/bin/sh
### Job name
#PBS -N pbs
### Declare job non-rerunable
#PBS -r n
### Output files
#PBS -j oe
### Mail to user
#PBS -m ae
### Queue name (n1, n2, n4, n20)
#PBS -q normal

#PBS -l select=16:ncpus=8:mpiprocs=2:ompthreads=4
### Walltime limit (hh:mm:ss)
#PBS -l walltime=100480:00:00

# This job's working directory
echo Working directory is $PBS_O_WORKDIR
cd $PBS_O_WORKDIR

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo This jobs runs on the following processors:
echo `cat $PBS_NODEFILE`
# Define number of processors
NPROCS=`wc -l < $PBS_NODEFILE`

## your parallel job

export FI_PROVIDER=tcp

#mpirun -n $NPROCS ~/local/bin/grafic2genus3D.exe ic_deltac 262.144 0 p 8 </dev/null >& loggenus
mpirun -n $NPROCS ~/local/bin/grafic2genus3D.exe ic_deltab 262.144 1 p 8 </dev/null >& loggenus
